-- Author : Rusiru Thushara

CREATE DATABASE NCMS;
USE NCMS;

CREATE TABLE MOH_OFFICER
(
    REGISTRATION_ID INT NOT NULL,
    NIC VARCHAR(15) UNIQUE NOT NULL,
    FNAME VARCHAR(50) NOT NULL,
    LNAME VARCHAR(60) NOT NULL,
    PRIMARY KEY (REGISTRATION_ID)
);

CREATE TABLE HOSPITAL
(
    HOSPITAL_ID INT NOT NULL,
    NAME VARCHAR(20),
    X_CORD DECIMAL NOT NULL,
    Y_CORD DECIMAL NOT NULL,
    NO_OF_BEDS INT,
    NO_OF_PATIENTS INT,
    NO_OF_AVAILABLE_BEDS INT,
    PRIMARY KEY (HOSPITAL_ID)
);

CREATE TABLE OFFICER_DETAIL
(
    HOSPITAL_ID INT NOT NULL,
    MOH_OFFICER_ID INT NOT NULL,
    PRIMARY KEY (HOSPITAL_ID, MOH_OFFICER_ID),
    FOREIGN KEY (HOSPITAL_ID) REFERENCES HOSPITAL(HOSPITAL_ID),
    FOREIGN KEY (MOH_OFFICER_ID) REFERENCES MOH_OFFICER(REGISTRATION_ID)
);

CREATE TABLE PATIENT
(
    NIC VARCHAR(15) NOT NULL UNIQUE,
    SERIAL_NO INT NOT NULL,
    FNAME VARCHAR(50) NOT NULL,
    LNAME VARCHAR(60) NOT NULL,
    HOSPITAL_ID INT,
    DOB DATE,
    X_CORD DECIMAL NOT NULL,
    Y_CORD DECIMAL NOT NULL,
    GENDER CHAR,
    DATE_IDENTIFIED DATE,
    GURDIAN_CONTACT INT,
    SEVERITY_LEVEL CHAR,
    IS_QUEUED BOOLEAN,
    QUEUE_NUMBER INT,
    PRIMARY KEY (SERIAL_NO),
    FOREIGN KEY (HOSPITAL_ID) REFERENCES HOSPITAL(HOSPITAL_ID)
);

CREATE TABLE ADMIDS
(
    PATIENT_ID INT NOT NULL,
    HOSPITAL_ID INT NOT NULL,
    BED_NUMBER INT,
    DATE_ADMITED DATE,
    PRIMARY KEY (PATIENT_ID, HOSPITAL_ID),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(SERIAL_NO),
    FOREIGN KEY (HOSPITAL_ID) REFERENCES HOSPITAL(HOSPITAL_ID)
);

CREATE TABLE STAFF
(
    NIC VARCHAR(15) NOT NULL UNIQUE,
    HOSPITAL_ID INT UNIQUE,
    MEMBER_ID INT NOT NULL,
    FNAME VARCHAR(50) NOT NULL,
    LNAME VARCHAR(60) NOT NULL,
    X_CORD DECIMAL NOT NULL,
    Y_CORD DECIMAL NOT NULL,
    PRIMARY KEY (HOSPITAL_ID, MEMBER_ID),
    FOREIGN KEY (HOSPITAL_ID) REFERENCES HOSPITAL(HOSPITAL_ID)
);

CREATE TABLE CHIEF_DOCTOR_DERECTOR
(
    REGISTRATION_ID INT NOT NULL,
    NIC VARCHAR(15) NOT NULL UNIQUE,
    HOSPITAL_ID INT NOT NULL,
    FNAME VARCHAR(50) NOT NULL,
    LNAME VARCHAR(60) NOT NULL,
    X_CORD DECIMAL NOT NULL,
    Y_CORD DECIMAL NOT NULL,
    MEMBERSHIP_ID INT NOT NULL,
    MOH_OFFICER_ID INT,
    PRIMARY KEY (REGISTRATION_ID),
    FOREIGN KEY (HOSPITAL_ID) REFERENCES HOSPITAL(HOSPITAL_ID),
    FOREIGN KEY (MOH_OFFICER_ID) REFERENCES MOH_OFFICER(REGISTRATION_ID)
);

CREATE TABLE NORMAL_DOCTOR
(
    REGISTRATION_ID INT NOT NULL,
    NIC VARCHAR(15) NOT NULL UNIQUE,
    HOSPITAL_ID INT,
    FNAME VARCHAR(50) NOT NULL,
    LNAME VARCHAR(60) NOT NULL,
    X_CORD DECIMAL NOT NULL,
    Y_CORD DECIMAL NOT NULL,
    CHIEF_DOCTOR_ID INT NOT NULL,
    PRIMARY KEY (REGISTRATION_ID),
    FOREIGN KEY (HOSPITAL_ID) REFERENCES HOSPITAL(HOSPITAL_ID),
    FOREIGN KEY (CHIEF_DOCTOR_ID) REFERENCES CHIEF_DOCTOR_DERECTOR(REGISTRATION_ID)
);

CREATE TABLE CONTACT_NUMBERS
(
    NIC VARCHAR(15) NOT NULL,
    PHONE_NO INT NOT NULL,
    PRIMARY KEY (NIC,PHONE_NO),
    FOREIGN KEY (NIC) REFERENCES PATIENT(NIC),
    FOREIGN KEY (NIC) REFERENCES NORMAL_DOCTOR(NIC),
    FOREIGN KEY (NIC) REFERENCES CHIEF_DOCTOR_DERECTOR(NIC),
    FOREIGN KEY (NIC) REFERENCES STAFF(NIC),
    FOREIGN KEY (NIC) REFERENCES MOH_OFFICER(NIC)
);

CREATE TABLE USERS
(
    USERNAME VARCHAR(16) NOT NULL,
    NIC VARCHAR(15),
    EMAIL VARCHAR(30),
    X_CORD DECIMAL NOT NULL,
    Y_CORD DECIMAL NOT NULL,
    VERIFIED_PHONE_NO INT,
    PRIMARY KEY (USERNAME)
);

CREATE TABLE LOGIN
(
    LOGIN_ID INT NOT NULL,
    USERNAME VARCHAR(16) NOT NULL,
    ROLE_ID INT NOT NULL,
    PASSWORD VARCHAR(20) NOT NULL,
    PRIMARY KEY (LOGIN_ID),
    FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME)
);

CREATE TABLE ROLE
(
    ROLE_ID INT NOT NULL,
    ROLE_NAME VARCHAR(50),
    USERNAME VARCHAR(16) NOT NULL,
    ACCESS_LEVEL CHAR,
    DESCRIPTION VARCHAR(100),
    PRIMARY KEY (ROLE_ID),
    FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME)
);
